CREATE TABLE IF NOT EXISTS users(
  id VARCHAR(36) PRIMARY KEY,
  email VARCHAR(300) UNIQUE NOT NULL,
  name VARCHAR(50) NOT NULL,
  password VARCHAR(256) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
)
