CREATE TABLE IF NOT EXISTS refresh_token (
  token VARCHAR(255) PRIMARY KEY,
  user_id VARCHAR(36) NOT NULL REFERENCES users(id),
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
